
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import GuardianBlockingContractArtifactJson from '../../aztec-guardians/target/guardians-GuardianBlocking.json' with { type: 'json' };
export const GuardianBlockingContractArtifact = loadContractArtifact(GuardianBlockingContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract GuardianBlocking;
 */
export class GuardianBlockingContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, GuardianBlockingContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, GuardianBlockingContract.artifact, wallet) as Promise<GuardianBlockingContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, portal: EthAddressLike) {
    return new DeployMethod<GuardianBlockingContract>(PublicKeys.default(), wallet, GuardianBlockingContractArtifact, GuardianBlockingContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, portal: EthAddressLike) {
    return new DeployMethod<GuardianBlockingContract>(publicKeys, wallet, GuardianBlockingContractArtifact, GuardianBlockingContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof GuardianBlockingContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<GuardianBlockingContract['methods'][M]>
  ) {
    return new DeployMethod<GuardianBlockingContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      GuardianBlockingContractArtifact,
      GuardianBlockingContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return GuardianBlockingContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(GuardianBlockingContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'config' | 'user_guardians' | 'approval_count' | 'guardian_count' | 'blocking_started' | 'user_blocked'> {
      return {
        config: {
      slot: new Fr(1n),
    },
user_guardians: {
      slot: new Fr(3n),
    },
approval_count: {
      slot: new Fr(4n),
    },
guardian_count: {
      slot: new Fr(5n),
    },
blocking_started: {
      slot: new Fr(6n),
    },
user_blocked: {
      slot: new Fr(7n),
    }
      } as ContractStorageLayout<'config' | 'user_guardians' | 'approval_count' | 'guardian_count' | 'blocking_started' | 'user_blocked'>;
    }
    

  public static get notes(): ContractNotes<'AddressNote' | 'ValueNote'> {
    return {
      AddressNote: {
          id: new NoteSelector(0),
        },
ValueNote: {
          id: new NoteSelector(1),
        }
    } as ContractNotes<'AddressNote' | 'ValueNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_guardian(guardian: struct) */
    add_guardian: ((guardian: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** approve_blocking(user: struct) */
    approve_blocking: ((user: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(portal: struct) */
    constructor: ((portal: EthAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initiate_blocking(user: struct) */
    initiate_blocking: ((user: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_user_blocked(user: struct) */
    is_user_blocked: ((user: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** remove_guardian(guardian: struct) */
    remove_guardian: ((guardian: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
