
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import NulWalletContractArtifactJson from '../../aztec-contracts/target/token_bridge-NulWallet.json' with { type: 'json' };
export const NulWalletContractArtifact = loadContractArtifact(NulWalletContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract NulWallet;
 */
export class NulWalletContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, NulWalletContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, NulWalletContract.artifact, wallet) as Promise<NulWalletContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, owner: AztecAddressLike, portal: EthAddressLike) {
    return new DeployMethod<NulWalletContract>(PublicKeys.default(), wallet, NulWalletContractArtifact, NulWalletContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, owner: AztecAddressLike, portal: EthAddressLike) {
    return new DeployMethod<NulWalletContract>(publicKeys, wallet, NulWalletContractArtifact, NulWalletContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof NulWalletContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<NulWalletContract['methods'][M]>
  ) {
    return new DeployMethod<NulWalletContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      NulWalletContractArtifact,
      NulWalletContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return NulWalletContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(NulWalletContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'config' | 'contacts' | 'votes' | 'vote_ended'> {
      return {
        config: {
      slot: new Fr(1n),
    },
contacts: {
      slot: new Fr(4n),
    },
votes: {
      slot: new Fr(5n),
    },
vote_ended: {
      slot: new Fr(6n),
    }
      } as ContractStorageLayout<'config' | 'contacts' | 'votes' | 'vote_ended'>;
    }
    

  public static get notes(): ContractNotes<'AddressNote' | 'UintNote' | 'VoteNote'> {
    return {
      AddressNote: {
          id: new NoteSelector(0),
        },
UintNote: {
          id: new NoteSelector(1),
        },
VoteNote: {
          id: new NoteSelector(2),
        }
    } as ContractNotes<'AddressNote' | 'UintNote' | 'VoteNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_contact(address: struct) */
    add_contact: ((address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(owner: struct, portal: struct) */
    constructor: ((owner: AztecAddressLike, portal: EthAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** contacts_length() */
    contacts_length: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_address_in_contacts(address: struct) */
    is_address_in_contacts: ((address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
